name: wsnet2
services:
  db:
    container_name: wsnet2-db
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wsnet2
      MYSQL_USER: wsnet
      MYSQL_PASSWORD: wsnetpass
      TZ: Asia/Tokyo
    command: --innodb_flush_log_at_trx_commit=2
    volumes:
      - ../server/sql:/docker-entrypoint-initdb.d
      - ../server/sql/trigger.d:/trigger.d
    ports:
      - 3306:3306
    entrypoint: bash -c 'chown -R mysql /trigger.d; docker-entrypoint.sh "$@"' docker-entrypoint.sh
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-hlocalhost",
          "--protocol=tcp",
          "--port=3306",
          "-uroot",
          "-p$$MYSQL_ROOT_PASSWORD",
        ]
      interval: 3s
      timeout: 1s
      retries: 10
      start_period: 1m
  builder:
    container_name: wsnet2-builder
    build: ../server
    image: wsnet2-arelo
    volumes:
      - ../:/repo
    working_dir: /repo/server
    command: bash -c 'make install-deps; arelo -p "**/*.{go,proto}" -i "**/.*" -i "**/*{_test,_string,.pb}.go" -i "cmd/wsnet2-{bot,tool}" -- make build'
  game:
    container_name: wsnet2-game
    depends_on:
      db:
        condition: service_healthy
    build: ../server
    image: wsnet2-arelo
    environment:
      WSNET2_GAME_HOSTNAME: wsnet2-game
      WSNET2_GAME_PUBLICNAME: localhost
      WSNET2_GAME_GRPCPORT: 19000
      WSNET2_GAME_WSPORT: 8000
    volumes:
      - ../:/repo
      - .log/:/var/log/wsnet2
    working_dir: /repo/server
    command: arelo -t "bin" -p "bin/wsnet2-game" -s SIGINT -- bin/wsnet2-game docker.toml
    ports:
      - 19000:19000
      - 8000:8000
      - 3000:3000
  hub:
    container_name: wsnet2-hub
    depends_on:
      db:
        condition: service_healthy
      game:
        condition: service_started
    build: ../server
    image: wsnet2-arelo
    environment:
      WSNET2_GAME_HOSTNAME: wsnet2-hub
      WSNET2_GAME_PUBLICNAME: localhost
      WSNET2_GAME_GRPCPORT: 19010
      WSNET2_GAME_WSPORT: 8010
    volumes:
      - ../:/repo
      - .log/:/var/log/wsnet2
    working_dir: /repo/server
    command: arelo -t "bin" -p "bin/wsnet2-hub" -s SIGINT -- bin/wsnet2-hub docker.toml
    ports:
      - 19010:19010
      - 8010:8010
      - 3010:3000
  lobby:
    container_name: wsnet2-lobby
    depends_on:
      db:
        condition: service_healthy
    build: ../server
    image: wsnet2-arelo
    volumes:
      - ../:/repo
      - .log/:/var/log/wsnet2
    working_dir: /repo/server
    command: arelo -t "bin" -p "bin/wsnet2-lobby" -- bin/wsnet2-lobby docker.toml
    ports:
      - 8080:8080
      - 3080:3000
