version: '3'
services:
  db:
    container_name: wsnet2-db
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wsnet2
      MYSQL_USER: wsnet
      MYSQL_PASSWORD: wsnetpass
      TZ: Asia/Tokyo
    command: --innodb_flush_log_at_trx_commit=2
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
  builder:
    container_name: wsnet2-builder
    build: .
    image: wsnet2-arelo
    volumes:
      - ../:/repo
    working_dir: /repo/server
    command: arelo -p "**/*.go" -i "**/.*" -i "**/*_test.go" -- make
  game:
    container_name: wsnet2-game
    depends_on:
      - db
    build: .
    image: wsnet2-arelo
    environment:
      WSNET2_GAME_HOSTNAME: wsnet2-game
      WSNET2_GAME_PUBLICNAME: localhost
      WSNET2_GAME_GRPCPORT: 19000
      WSNET2_GAME_WSPORT: 8000
    volumes:
      - ../:/repo
      - .log/:/var/log/wsnet2
    working_dir: /repo/server
    command: arelo -t "bin" -p "bin/wsnet2-game" -s SIGINT -- bin/wsnet2-game docker.toml
    entrypoint: /wait-for-it.sh wsnet2-db:3306 -s -t 0 --
    ports:
      - 19000:19000
      - 8000:8000
      - 3000:3000
  hub:
    container_name: wsnet2-hub
    depends_on:
      - db
      - game
    build: .
    image: wsnet2-arelo
    environment:
      WSNET2_GAME_HOSTNAME: wsnet2-hub
      WSNET2_GAME_PUBLICNAME: localhost
      WSNET2_GAME_GRPCPORT: 19010
      WSNET2_GAME_WSPORT: 8010
    volumes:
      - ../:/repo
      - .log/:/var/log/wsnet2
    working_dir: /repo/server
    command: arelo -t "bin" -p "bin/wsnet2-hub" -s SIGINT -- bin/wsnet2-hub docker.toml
    entrypoint: /wait-for-it.sh wsnet2-db:3306 -s -t 0 --
    ports:
      - 19010:19010
      - 8010:8010
      - 3010:3000
  lobby:
    container_name: wsnet2-lobby
    depends_on:
      - db
    build: .
    image: wsnet2-arelo
    volumes:
      - ../:/repo
      - .log/:/var/log/wsnet2
    working_dir: /repo/server
    command: arelo -t "bin" -p "bin/wsnet2-lobby" -- bin/wsnet2-lobby docker.toml
    entrypoint: /wait-for-it.sh wsnet2-db:3306 -s -t 0 --
    ports:
      - 8080:8080
      - 3080:3000
