version: '3'
services:
  game2:
    container_name: wsnet2-game2
    depends_on:
      - db
    build: .
    image: wsnet2-arelo
    environment:
      WSNET2_GAME_HOSTNAME: wsnet2-game2
      WSNET2_GAME_PUBLICNAME: localhost
      WSNET2_GAME_GRPCPORT: 19001
      WSNET2_GAME_WSPORT: 8001
    volumes:
      - ../:/repo
      - .log/2:/var/log/wsnet2
    working_dir: /repo/server
    command: arelo -t "bin" -p "bin/wsnet2-game" -s SIGINT -- bin/wsnet2-game docker.toml
    entrypoint: /wait-for-it.sh wsnet2-db:3306 -s -t 0 --
    ports:
      - 19001:19001
      - 8001:8001
      - 3001:3000
  hub2:
    container_name: wsnet2-hub2
    depends_on:
      - db
      - game
    build: .
    image: wsnet2-arelo
    environment:
      WSNET2_GAME_HOSTNAME: wsnet2-hub2
      WSNET2_GAME_PUBLICNAME: localhost
      WSNET2_GAME_GRPCPORT: 19011
      WSNET2_GAME_WSPORT: 8011
    volumes:
      - ../:/repo
      - .log/2:/var/log/wsnet2
    working_dir: /repo/server
    command: arelo -t "bin" -p "bin/wsnet2-hub" -s SIGINT -- bin/wsnet2-hub docker.toml
    entrypoint: /wait-for-it.sh wsnet2-db:3306 -s -t 0 --
    ports:
      - 19011:19011
      - 8011:8011
      - 3011:3000
