version: '3'
services:
  db:
    container_name: wsnet2-db
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wsnet2
      MYSQL_USER: wsnet
      MYSQL_PASSWORD: wsnetpass
      TZ: Asia/Tokyo
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
  game:
    container_name: wsnet2-game
    depends_on:
      - db
    build: .
    image: wsnet2-arelo
    environment:
      WSNET2_GAME_HOSTNAME: wsnet2-game
      WSNET2_GAME_PUBLICNAME: localhost
    volumes:
      - ./:/work
    working_dir: /work
    command: bash -c 'make generate && arelo -p "**/*.go" -p "./docker.toml" -i "**/.*" -i "cmd/wsnet2-\{lobby,bot\}" -d 3s -- go run cmd/wsnet2-game/main.go docker.toml'
    entrypoint: /wait-for-it.sh wsnet2-db:3306 --
    ports:
      - 19000:19000
      - 8000:8000
      - 3000:3000
  hub:
    container_name: wsnet2-hub
    depends_on:
      - db
      - game
    build: .
    image: wsnet2-arelo
    environment:
      WSNET2_GAME_HOSTNAME: wsnet2-hub
      WSNET2_GAME_PUBLICNAME: localhost
    volumes:
      - ./:/work
    working_dir: /work
    command: bash -c 'make generate && arelo -p "**/*.go" -p "./docker.toml" -i "**/.*" -i "cmd/wsnet2-\{lobby,bot\}" -d 3s -- go run cmd/wsnet2-hub/main.go docker.toml'
    entrypoint: /wait-for-it.sh wsnet2-db:3306 --
    ports:
      - 19001:19001
      - 8001:8001
      - 3002:3002
  lobby:
    container_name: wsnet2-lobby
    depends_on:
      - db
    build: .
    image: wsnet2-arelo
    volumes:
      - ./:/work
    working_dir: /work
    command: bash -c 'make generate && arelo -p "**/*.go" -p "./docker.toml" -i "**/.*" -i "cmd/wsnet2-\{game,bot\}" -d 3s -- go run cmd/wsnet2-lobby/main.go docker.toml'
    entrypoint: /wait-for-it.sh wsnet2-db:3306 --
    ports:
      - 8080:8080
      - 3001:3001
