[Database]
host = "wsnet2-db"
port = 3306
user = "wsnet"
password = "wsnetpass"
dbname = "wsnet2"

[Game]
log_stdout_console = true
pprof_port = 3000

default_deadline = 5
default_loglevel = 5
max_room_num = 999999

[Hub]
log_stdout_console = true
pprof_port = 3000

default_loglevel = 5

[Lobby]
log_stdout_console = true
hostname = "localhost"
net = "tcp"
port = 8080
pprof_port = 3000
loglevel = 5
