[Database]
host = "wsnet2-db"
port = 3306
user = "wsnet"
password = "wsnetpass"
dbname = "wsnet2"

[Game]
grpc_addr = ":19000"
websocket_port = 8000
pprof_addr = ":3000"

default_deadline = 5
default_loglevel = 4

[Lobby]
hostname = "localhost"
net = "tcp"
addr = ":8080"
pprof_addr = ":3001"
