version: '3'
services:
  db:
    container_name: wsnet2-db
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wsnet2
      MYSQL_USER: wsnet
      MYSQL_PASSWORD: wsnetpass
      TZ: Asia/Tokyo
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
  builder:
    container_name: wsnet2-builder
    image: wsnet2-arelo
    volumes:
      - ../:/repo
    working_dir: /repo/server
    command: arelo -v -p "**/*.go" -i "**/.*" -i "**/*_test.go" -- make
  game:
    container_name: wsnet2-game
    depends_on:
      - db
    build: .
    image: wsnet2-arelo
    environment:
      WSNET2_GAME_HOSTNAME: wsnet2-game
      WSNET2_GAME_PUBLICNAME: localhost
    volumes:
      - ../:/repo
      - .log/:/var/log/wsnet2
    working_dir: /repo/server
    command: arelo -t "bin" -p "bin/wsnet2-game" -- bin/wsnet2-game docker.toml
    entrypoint: /wait-for-it.sh wsnet2-db:3306 --
    ports:
      - 19000:19000
      - 8000:8000
      - 3000:3000
  hub:
    container_name: wsnet2-hub
    depends_on:
      - db
      - game
    build: .
    image: wsnet2-arelo
    environment:
      WSNET2_GAME_HOSTNAME: wsnet2-hub
      WSNET2_GAME_PUBLICNAME: localhost
    volumes:
      - ../:/repo
      - .log/:/var/log/wsnet2
    working_dir: /repo/server
    command: arelo -t "bin" -p "bin/wsnet2-hub" -- bin/wsnet2-hub docker.toml
    entrypoint: /wait-for-it.sh wsnet2-db:3306 --
    ports:
      - 19001:19001
      - 8001:8001
      - 3002:3002
  lobby:
    container_name: wsnet2-lobby
    depends_on:
      - db
    build: .
    image: wsnet2-arelo
    volumes:
      - ../:/repo
      - .log/:/var/log/wsnet2
    working_dir: /repo/server
    command: arelo -t "bin" -p "bin/wsnet2-lobby" -- bin/wsnet2-lobby docker.toml
    entrypoint: /wait-for-it.sh wsnet2-db:3306 --
    ports:
      - 8080:8080
      - 3001:3001
