name: WSNet2 server ci

on:
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/wsnet2-server.yml'
      - 'server/**'

jobs:
  test:
    runs-on: "ubuntu-latest"
    defaults:
      run:
        working-directory: server
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.19.0'
          #cache: true  # todo: enable cache after adding go.sum file

      - uses: arduino/setup-protoc@v1
        with:
          version: '3.x'

      - uses: actions/checkout@v3

      - name: Build
        run: make all

      - name: Run go test
        run: go test ./...

      - uses: reviewdog/action-setup@v1

      - name: Run staticcheck
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          staticcheck ./... 2>&1 | reviewdog -f staticcheck -reporter=github-pr-check

  run-bot:
    runs-on: "ubuntu-latest"
    needs: test
    defaults:
      run:
        working-directory: server
    steps:
      - uses: actions/checkout@v3

      - run: |
          docker compose up -d
          until [ -f bin/wsnet2-bot ]
          do
            sleep 5
          done
          bin/wsnet2-bot
          docker compose logs
