name: WSNet2 dotnet ci

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: [ wsnet2-ci ]
    defaults:
      run:
        working-directory: wsnet2-dotnet
    steps:
      - uses: actions/checkout@v2
      - name: dotnet build
        run:  dotnet build WSNet2.sln
      - name: dotnet test
        run:  dotnet test WSNet2.sln
