name: WSNet2 server ci

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'server/**'

jobs:
  build:
    runs-on: "ubuntu-latest"
    defaults:
      run:
        working-directory: server
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.19.0'

      - uses: arduino/setup-protoc@v1
        with:
          version: '3.x'

      - uses: actions/checkout@v3

      - name: Build
        run: make all

      - name: Run go test
        run: go test ./...

      - uses: reviewdog/action-staticcheck@v1
        with:
          workdir: server
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-check
          fail_on_error: true
