name: WSNet2 server ci

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'server/**'

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.19.0'

      - uses: actions/checkout@v3

      - name: Build and Test
        working-directory: server
        run: docker-compose run --rm builder /bin/bash -eo pipefail -c "make all" && go test ./...

      - uses: reviewdog/action-staticcheck@v1
        with:
          workdir: server
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-check
          fail_on_error: true
