name: WSNet2 server ci

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'server/**'

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3

      - name: make and test
        working-directory: server
        run: docker-compose run --rm builder /bin/bash -eo pipefail -c "make all"

      - uses: actions/setup-go@v3
        with:
          go-version: '^1.19.0'

      - name: Run staticcheck
        working-directory: server
        run:
          go install honnef.co/go/tools/cmd/staticcheck@latest
          echo "::add-matcher::.github/staticcheck-matcher.json"
          staticcheck ./...
