name: WSNet2 server ci

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3

      - name: make and test
        working-directory: server
        run: docker-compose run --rm builder /bin/bash -eo pipefail -c "make all"

      - uses: dominikh/staticcheck-action@v1.2.0
        with:
          working-directory: server
