name: WSNet2 dotnet ci

on:
  push:
    branches: [ master, ci-work ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: [ wsnet2-ci ]
    defaults:
      run:
        working-directory: wsnet2-dotnet
    steps:
      - uses: actions/checkout@v2
      - name: dotnet build
        run: ./build-commit
      - name: dotnet test
        run: dotnet test WSNet2.Core.Test/WSNet2.Core.Test.csproj
