name: WSNet2 dotnet ci

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: [ ubuntu-latest ]
    defaults:
      run:
        working-directory: wsnet2-dotnet
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "6.x"
      - name: dotnet build
        run:  dotnet build WSNet2.sln
      - name: dotnet test
        run:  dotnet test WSNet2.sln
