name: WSNet2 server ci

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: [ ubuntu-latest ]
    env:
      REVIEWDOG_GITHUB_API_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v2
      - name: make and test
        run: cd server && docker-compose run --rm builder /bin/bash -eo pipefail -c "make all && go test ./... && ./bin/staticcheck -f=json -fail '' ./... > ../staticcheck-output.json"
      - uses: reviewdog/action-setup@v1
      - name: staticcheck pr comment
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: cat staticcheck-output.json | sed s#/repo/##g | jq -f ${{ github.workspace }}/.github/workflows/staticcheck-to-rdjsonl.jq -c | reviewdog -tee -f=rdjsonl -name=staticcheck -reporter=github-pr-review -level=warning
